---
name: pipobscure.dev
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Personal Site of Philipp Dunkel
plugins:
  - jekyll-paginate
highlighter: rouge
paginate: 20
